extends:
  - standard
  - plugin:@typescript-eslint/recommended
plugins:
  - "@typescript-eslint"

parser: "@typescript-eslint/parser"
env:
  es6: true
  node: true
parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    ts: true
rules:
  "@typescript-eslint/no-namespace": off